# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'WebKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebKit
  pod 'AFNetworking', '~> 3.0'

end
